### ISSUE TITLE
[Bug]: PathTooLongException in OperationParameterInjectionGenerator

### ISSUE THREAD

**Issue by Pjotrtje** [CoreWCF/CoreWCF#1239]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.4.1

### Describe expected behavior

No errors in OperationParameterInjectionGenerator after update from v1.3.2 to 1.4.1

### Describe actual behavior

"Generator 'OperationParameterInjectionGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'PathTooLongException' with message 'The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.'"

Errors since update from 1.3.2 to 1.4.1 

Hello,
Since we updated we have issues with the OperationParameterInjectionGenerator:

I think the issue is introduced with:
https://github.com/CoreWCF/CoreWCF/pull/1183/files

The filenames now are way longer; something like x2. And for us it is a really breaking change. If there is a way to opt in or out for the longer file names that would be nice.

Greetings,
Pieter

### Which binding

BasicHttp

### security

None

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
using CoreWCF;

namespace Xxxxxx.Xx.Xxxxxxxxxxxxxxx.Host.Xxxxxxxxxxxxx.CoreWcfContract.V2;

[ServiceContract]
public interface IXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
{
    [OperationContract]
    GetClustersResponse GetClusters(GetClustersRequest request);
}

public record GetClustersResponse();
public record GetClustersRequest();

-----


using CoreWCF;
using Xxxxxx.Xx.Xxxxxxxxxxxxxxx.Host.Xxxxxxxxxxxxx.CoreWcfContract.V2;

namespace Xxxxxx.Xx.Xxxxxxxxxxxxxxx.Host.Xxxxxxxxxxxxx.Xxxxxxxx.V2.Xxxxxxxxxxxxxxxxxxxxxxxxxxxxx;

[ServiceBehavior(
	InstanceContextMode = InstanceContextMode.Single,
	ConcurrencyMode = ConcurrencyMode.Multiple)]
public partial class Xxxxxxxxxxxxxxxxxxxxxxxxxxxxx : IXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
{

    private static GetClustersResponse GetClusters(GetClustersRequest request, [Injected] SomeService someService)
    {
        return someService.GetClusters(request);
    }
}
```

### Stacktrace if any

```shell
"Generator 'OperationParameterInjectionGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'PathTooLongException' with message 'The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.'"
```

**Comment by g7ed6e** [comment]
@Pjotrtje the full names including namespaces of both ServiceContract and service implementation are now included in the generated file name to disambiguate. I will have a look to this.

**Comment by Pjotrtje** [comment]
@g7ed6e , it think it is the filename. But not completely sure. But seeing your proposed changes in the linked PR I imagine it does not really matter anymore 😃

**Comment by g7ed6e** [comment]
> @g7ed6e , it think it is the filename. But not completely sure. But seeing your proposed changes in the linked PR I imagine it does not really matter anymore 😃

Indeed I now output a unique file which name is fixed  as `OperationParameterInjector.g.cs`. This is the same approach as the `[LoggerMessage]` source gen from Microsoft.Extensions.Logging.
