### PR TITLE
Fix PathTooLongException in OperationParameterInjectorGenerator

### LINKED ISSUE #1239: [Bug]: PathTooLongException in OperationParameterInjectionGenerator
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.4.1

### Describe expected behavior

No errors in OperationParameterInjectionGenerator after update from v1.3.2 to 1.4.1

### Describe actual behavior

"Generator 'OperationParameterInjectionGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'PathTooLongException' with message 'The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.'"

Errors since update from 1.3.2 to 1.4.1 

Hello,
Since we updated we have issues with the OperationParameterInjectionGenerator:

I think the issue is introduced with:
https://github.com/CoreWCF/CoreWCF/pull/1183/files

The filenames now are way longer; something like x2. And for us it is a really breaking change. If there is a way to opt in or out for the longer file names that would be nice.

Greetings,
Pieter

### Which binding

BasicHttp

### security

None

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
using CoreWCF;

namespace Xxxxxx.Xx.Xxxxxxxxxxxxxxx.Host.Xxxxxxxxxxxxx.CoreWcfContract.V2;

[ServiceContract]
public interface IXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
{
    [OperationContract]
    GetClustersResponse GetClusters(GetClustersRequest request);
}

public record GetClustersResponse();
public record GetClustersRequest();

-----


using CoreWCF;
using Xxxxxx.Xx.Xxxxxxxxxxxxxxx.Host.Xxxxxxxxxxxxx.CoreWcfContract.V2;

namespace Xxxxxx.Xx.Xxxxxxxxxxxxxxx.Host.Xxxxxxxxxxxxx.Xxxxxxxx.V2.Xxxxxxxxxxxxxxxxxxxxxxxxxxxxx;

[ServiceBehavior(
	InstanceContextMode = InstanceContextMode.Single,
	ConcurrencyMode = ConcurrencyMode.Multiple)]
public partial class Xxxxxxxxxxxxxxxxxxxxxxxxxxxxx : IXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
{

    private static GetClustersResponse GetClusters(GetClustersRequest request, [Injected] SomeService someService)
    {
        return someService.GetClusters(request);
    }
}
```

### Stacktrace if any

```shell
"Generator 'OperationParameterInjectionGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'PathTooLongException' with message 'The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.'"
```

### PR DESCRIPTION
**Pull request by g7ed6e**
Place code generated by OperationParameterInjectionGenerator in a short fixed filename named
OperationParameterInjection.g.cs

Resolves #1239

### CODE REVIEW

**Comment by g7ed6e** [comment]
TODO: Add missing nullable restore at the end of the generated file

**Review by mconnew — APPROVED** [review]
